### ISSUE TITLE
Failed to start with older version v.2.2.14

### ISSUE THREAD

**Issue by yongkeecho** [cloudfoundry/dotnet-core-buildpack#316]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
cf version 6.43.0+815ea2f3d.2019-02-20

What version of the buildpack you are using?
v2.2.14

We have only 'cflinuxfs2' stack and dotnet-core-buildpack v2.2.14 is the most recent version we can use.
Starting my API with the below manifest file had worked without any issue.
```
---
applications:
- name: my-api
  buildpacks:
   - https://github.com/cloudfoundry/dotnet-core-buildpack.git#v2.2.14
  memory: 1024M
```

Today it fails with the message below:
```
> cf start my-api
Your API version is no longer supported. Upgrade to a newer version of the API. Please refer to https://github.com/cloudfoundry/cli/wiki/Versioning-Policy#cf-cli-minimum-supported-version

Starting app my-api in org bio / space team as user@my.com...

Staging app and tracing logs...
   Creating container
   Successfully created container
   Downloading app package...
   Downloaded app package (13.7M)
   Failed to clone git repository at https://github.com/cloudfoundry/dotnet-core-buildpack.git
   Exit status 1
```
